google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Models/PageResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoogleCloudPrint.Web.Models
{
    public class PageResponse
    {
        public string cMessage { get; set; }
        public bool isSuccess { get; set; }
    }
}

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Models/PrinterModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GoogleCloudPrint.Web.Models
{
    public class PrinterModel
    {
        [Required(ErrorMessage = "* Required")]
        public string PrinterId { get; set; }

        [Required(ErrorMessage = "* Required")]
        public string title { get; set; }

        public bool isPrintFromUrl { get; set; }

        //Print from url
        public string url { get; set; }

        //Print by uploading file
        public string strFileName { get; set; }
        public byte[] document { get; set; }
        public string mimeType { get; set; }
    }
}

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Controllers/AcceptPendingInvitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoogleCloudPrint.Lib;
using GoogleCloudPrint.Web.Models;

namespace GoogleCloudPrint.Web.Controllers
{
    public class AcceptPendingInvitesController : Controller
    {
        public ActionResult Index()
        {
            if (TempData["TDMessage"] != null)
            {
                ViewBag.PageResp = TempData["TDMessage"];
                TempData.Remove("TDMessage");
            }

            return View();
        }

        [HttpPost]
        public ActionResult IndexPost(string printerId = "")
        {
            try
            {
                if (!string.IsNullOrEmpty(printerId))
                {
                    CloudHelper.AcceptAnyPendingInvites(printerId);
                    TempData.Add("TDMessage", new PageResponse { cMessage = "Printer added successfully!", isSuccess = true });
                }
                else
                {
                    TempData.Add("TDMessage", new PageResponse { cMessage = "Please enter PrinterId", isSuccess = false });
                }
            }
            catch (Exception ex)
            {
                TempData.Add("TDMessage", new PageResponse { cMessage = ex.Message, isSuccess = false });
            }

            return RedirectToAction("Index");
        }

    }
}

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Controllers/CloudPrintController.cs
using GoogleCloudPrint.Lib;
using GoogleCloudPrint.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleCloudPrint.Web.Controllers
{
    public class CloudPrintController : Controller
    {
        // GET: CloudPrint
        public ActionResult Index()
        {
            ViewBag.PrinterList = CloudHelper.GetPrinterList().Select(x => new SelectListItem { Text = x.Key, Value = x.Value }).ToList();

            if (TempData["TDMessage"] != null)
            {
                ViewBag.PageResp = TempData["TDMessage"];
                TempData.Remove("TDMessage");
            }

            var oRet = new PrinterModel();
            return View(oRet);
        }

        [HttpPost]
        public ActionResult IndexPost(PrinterModel oModel, HttpPostedFileBase fileUpload)
        {
            try
            {
                if (!oModel.isPrintFromUrl)
                {
                    if (fileUpload == null)
                    {
                        throw new Exception("Please upload file!");
                    }

                    oModel.strFileName = fileUpload.FileName;

                    using (var binaryReader = new BinaryReader(fileUpload.InputStream))
                    {
                        oModel.document = binaryReader.ReadBytes(fileUpload.ContentLength);
                    }

                    CloudHelper.PrintUploadedFile(oModel.PrinterId, oModel.title, oModel.strFileName, oModel.document);

                }
                else
                {
                    if (string.IsNullOrEmpty(oModel.url))
                    {
                        throw new Exception("Please enter url to print!");
                    }

                    CloudHelper.PrintOnlineUrl(oModel.PrinterId, oModel.title, oModel.url);
                }

                TempData.Add("TDMessage", new PageResponse { cMessage = "Printer request sent successfully!", isSuccess = true });

            }
            catch (Exception ex)
            {
                TempData.Add("TDMessage", new PageResponse { cMessage = ex.Message, isSuccess = false });
            }

            return RedirectToAction("Index");
        }


    }
}

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Controllers/HomeController.cs
using GoogleCloudPrint.Lib;
using GoogleCloudPrint.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleCloudPrint.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var allPrinters = CloudHelper.GetPrinterList();
            ViewBag.allPrinters = allPrinters;

            return View();
        }

      
    }
}

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Views/AcceptPendingInvites/Index.cshtml
@{
    ViewBag.Title = "Add Printer Id";

    GoogleCloudPrint.Web.Models.PageResponse oResp = null;
    if (ViewBag.PageResp != null)
    {
        oResp = (GoogleCloudPrint.Web.Models.PageResponse)ViewBag.PageResp;
    }
}

<h2>Add Printer Id</h2>

@if (oResp != null)
{
    if (oResp.isSuccess)
    {
        <p class="alert alert-success">@oResp.cMessage</p>
    }
    else
    {
        <p class="alert alert-danger">@oResp.cMessage</p>
    }
}

<div class="row">
    <div class="col-md-12 form-inline">
        @using (Html.BeginForm("IndexPost", "AcceptPendingInvites",FormMethod.Post))
        {
            <input type="text" class="form-control" required name="printerId" value="" />
            <input type="submit" class="btn btn-primary" value="Add Printer" />
        }
    </div>
</div>

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Views/CloudPrint/Index.cshtml
@model GoogleCloudPrint.Web.Models.PrinterModel
@{
    ViewBag.Title = "Cloud Print";

    GoogleCloudPrint.Web.Models.PageResponse oResp = null;
    if (ViewBag.PageResp != null)
    {
        oResp = (GoogleCloudPrint.Web.Models.PageResponse)ViewBag.PageResp;
    }
}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#isPrintFromUrl").change(handlePrintTypeChange);
        });

        function handlePrintTypeChange() {
            if ($("#isPrintFromUrl").is(":checked")) {
                $("#divUrl").show();
                $("#divUploadFile").hide();
            }
            else {
                $("#divUrl").hide();
                $("#divUploadFile").show();
            }
        }
    </script>
}

<h2>Cloud Print</h2>

@if (oResp != null)
{
    if (oResp.isSuccess)
    {
        <p class="alert alert-success">@oResp.cMessage</p>
    }
    else
    {
        <p class="alert alert-danger">@oResp.cMessage</p>
    }
}

@using (Html.BeginForm("IndexPost", "CloudPrint", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label>Printer:</label>
        @Html.DropDownListFor(x => x.PrinterId, (List<SelectListItem>)ViewBag.PrinterList, "Select", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PrinterId)
    </div>
    <div class="form-group">
        <label>Print Title:</label>
        @Html.TextBoxFor(x => x.title, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.title)
    </div>
    <div class="checkbox">
        <label> @Html.CheckBoxFor(x => x.isPrintFromUrl) Is Print From Url</label>
    </div>
    <div id="divUrl" style="display:none;" class="form-group">
        <label>Url:</label>
        @Html.TextBoxFor(x => x.url, new { @class = "form-control" })
    </div>
    <div id="divUploadFile" class="form-group">
        <label>Upload File:</label>
        <input id="fileUpload" name="fileUpload" type="file" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Print</button>
}

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "All Printers";
    var allPrinters = (List<KeyValuePair<string,string>>) ViewBag.allPrinters;
}

<div class="jumbotron">
    <h1>All Printers</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <ul>
            @foreach (var itmPrinter in allPrinters)
            {
                <li>@itmPrinter.Key -- @itmPrinter.Value</li>
            }
        </ul>
    </div>
</div>

google-cloud-print-using-asp.net-mvc/GoogleCloudPrint.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Google Print POC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Accept Pending Invites", "Index", "AcceptPendingInvites")</li>
                    <li>@Html.ActionLink("Cloud Print", "Index", "CloudPrint")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HealthTech India</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>